// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/crypto.dart';
import 'api/decode.dart';
import 'api/piv_crypto.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  PivPrivateKeyData dco_decode_box_autoadd_piv_private_key_data(dynamic raw);

  @protected
  SelfSignedCertificateParams
      dco_decode_box_autoadd_self_signed_certificate_params(dynamic raw);

  @protected
  X509CertData dco_decode_box_autoadd_x_509_cert_data(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PivPrivateKeyData? dco_decode_opt_box_autoadd_piv_private_key_data(
      dynamic raw);

  @protected
  X509CertData? dco_decode_opt_box_autoadd_x_509_cert_data(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  PivImportFileData dco_decode_piv_import_file_data(dynamic raw);

  @protected
  PivPrivateKeyData dco_decode_piv_private_key_data(dynamic raw);

  @protected
  PivPublicKeyData dco_decode_piv_public_key_data(dynamic raw);

  @protected
  SelfSignedCertificateParams dco_decode_self_signed_certificate_params(
      dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  X509CertData dco_decode_x_509_cert_data(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  PivPrivateKeyData sse_decode_box_autoadd_piv_private_key_data(
      SseDeserializer deserializer);

  @protected
  SelfSignedCertificateParams
      sse_decode_box_autoadd_self_signed_certificate_params(
          SseDeserializer deserializer);

  @protected
  X509CertData sse_decode_box_autoadd_x_509_cert_data(
      SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PivPrivateKeyData? sse_decode_opt_box_autoadd_piv_private_key_data(
      SseDeserializer deserializer);

  @protected
  X509CertData? sse_decode_opt_box_autoadd_x_509_cert_data(
      SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  PivImportFileData sse_decode_piv_import_file_data(
      SseDeserializer deserializer);

  @protected
  PivPrivateKeyData sse_decode_piv_private_key_data(
      SseDeserializer deserializer);

  @protected
  PivPublicKeyData sse_decode_piv_public_key_data(SseDeserializer deserializer);

  @protected
  SelfSignedCertificateParams sse_decode_self_signed_certificate_params(
      SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  X509CertData sse_decode_x_509_cert_data(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_piv_private_key_data(
      PivPrivateKeyData self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_self_signed_certificate_params(
      SelfSignedCertificateParams self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_x_509_cert_data(
      X509CertData self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_piv_private_key_data(
      PivPrivateKeyData? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_x_509_cert_data(
      X509CertData? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
      Uint8List? self, SseSerializer serializer);

  @protected
  void sse_encode_piv_import_file_data(
      PivImportFileData self, SseSerializer serializer);

  @protected
  void sse_encode_piv_private_key_data(
      PivPrivateKeyData self, SseSerializer serializer);

  @protected
  void sse_encode_piv_public_key_data(
      PivPublicKeyData self, SseSerializer serializer);

  @protected
  void sse_encode_self_signed_certificate_params(
      SelfSignedCertificateParams self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_x_509_cert_data(X509CertData self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
