// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/crypto.dart';
import 'api/decode.dart';
import 'api/piv_crypto.dart';
import 'api/protocol.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_CtapPinSessionPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinSession;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_CtapPinTokenPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinToken;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ProtocolOperationPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtocolOperation;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ProtocolProfilePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtocolProfile;

  @protected
  CtapPinSession
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinSession(
    dynamic raw,
  );

  @protected
  CtapPinToken
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinToken(
    dynamic raw,
  );

  @protected
  ProtocolOperation
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtocolOperation(
    dynamic raw,
  );

  @protected
  ProtocolProfile
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtocolProfile(
    dynamic raw,
  );

  @protected
  CtapPinSession
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinSession(
    dynamic raw,
  );

  @protected
  CtapPinToken
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinToken(
    dynamic raw,
  );

  @protected
  ProtocolOperation
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtocolOperation(
    dynamic raw,
  );

  @protected
  ProtocolProfile
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtocolProfile(
    dynamic raw,
  );

  @protected
  CtapPinSession
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinSession(
    dynamic raw,
  );

  @protected
  CtapPinToken
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinToken(
    dynamic raw,
  );

  @protected
  ProtocolProfile
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtocolProfile(
    dynamic raw,
  );

  @protected
  CtapPinSession
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinSession(
    dynamic raw,
  );

  @protected
  CtapPinToken
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinToken(
    dynamic raw,
  );

  @protected
  ProtocolOperation
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtocolOperation(
    dynamic raw,
  );

  @protected
  ProtocolProfile
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtocolProfile(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AdminAction dco_decode_admin_action(dynamic raw);

  @protected
  AdminConfigurationPatch dco_decode_admin_configuration_patch(dynamic raw);

  @protected
  AdminProgress dco_decode_admin_progress(dynamic raw);

  @protected
  AdminReadOperation dco_decode_admin_read_operation(dynamic raw);

  @protected
  AdminResult dco_decode_admin_result(dynamic raw);

  @protected
  AdminValueKind dco_decode_admin_value_kind(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BootstrapIdentityStep dco_decode_bootstrap_identity_step(dynamic raw);

  @protected
  CtapPinSession
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinSession(
    dynamic raw,
  );

  @protected
  CtapPinToken
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinToken(
    dynamic raw,
  );

  @protected
  ProtocolProfile
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtocolProfile(
    dynamic raw,
  );

  @protected
  AdminConfigurationPatch dco_decode_box_autoadd_admin_configuration_patch(
    dynamic raw,
  );

  @protected
  AdminProgress dco_decode_box_autoadd_admin_progress(dynamic raw);

  @protected
  AdminResult dco_decode_box_autoadd_admin_result(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  PivPrivateKeyData dco_decode_box_autoadd_piv_private_key_data(dynamic raw);

  @protected
  ProtocolError dco_decode_box_autoadd_protocol_error(dynamic raw);

  @protected
  SelfSignedCertificateParams
  dco_decode_box_autoadd_self_signed_certificate_params(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw);

  @protected
  X509CertData dco_decode_box_autoadd_x_509_cert_data(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  CtapPinSession?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinSession(
    dynamic raw,
  );

  @protected
  CtapPinToken?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinToken(
    dynamic raw,
  );

  @protected
  ProtocolProfile?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtocolProfile(
    dynamic raw,
  );

  @protected
  AdminProgress? dco_decode_opt_box_autoadd_admin_progress(dynamic raw);

  @protected
  AdminResult? dco_decode_opt_box_autoadd_admin_result(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  PivPrivateKeyData? dco_decode_opt_box_autoadd_piv_private_key_data(
    dynamic raw,
  );

  @protected
  ProtocolError? dco_decode_opt_box_autoadd_protocol_error(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw);

  @protected
  X509CertData? dco_decode_opt_box_autoadd_x_509_cert_data(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  PivCredentialOperation dco_decode_piv_credential_operation(dynamic raw);

  @protected
  PivImportFileData dco_decode_piv_import_file_data(dynamic raw);

  @protected
  PivPrivateKeyData dco_decode_piv_private_key_data(dynamic raw);

  @protected
  PivPublicKeyData dco_decode_piv_public_key_data(dynamic raw);

  @protected
  PivReadOperation dco_decode_piv_read_operation(dynamic raw);

  @protected
  ProtocolError dco_decode_protocol_error(dynamic raw);

  @protected
  ProtocolStep dco_decode_protocol_step(dynamic raw);

  @protected
  SelfSignedCertificateParams dco_decode_self_signed_certificate_params(
    dynamic raw,
  );

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  X509CertData dco_decode_x_509_cert_data(dynamic raw);

  @protected
  CtapPinSession
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinSession(
    SseDeserializer deserializer,
  );

  @protected
  CtapPinToken
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinToken(
    SseDeserializer deserializer,
  );

  @protected
  ProtocolOperation
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtocolOperation(
    SseDeserializer deserializer,
  );

  @protected
  ProtocolProfile
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtocolProfile(
    SseDeserializer deserializer,
  );

  @protected
  CtapPinSession
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinSession(
    SseDeserializer deserializer,
  );

  @protected
  CtapPinToken
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinToken(
    SseDeserializer deserializer,
  );

  @protected
  ProtocolOperation
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtocolOperation(
    SseDeserializer deserializer,
  );

  @protected
  ProtocolProfile
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtocolProfile(
    SseDeserializer deserializer,
  );

  @protected
  CtapPinSession
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinSession(
    SseDeserializer deserializer,
  );

  @protected
  CtapPinToken
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinToken(
    SseDeserializer deserializer,
  );

  @protected
  ProtocolProfile
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtocolProfile(
    SseDeserializer deserializer,
  );

  @protected
  CtapPinSession
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinSession(
    SseDeserializer deserializer,
  );

  @protected
  CtapPinToken
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinToken(
    SseDeserializer deserializer,
  );

  @protected
  ProtocolOperation
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtocolOperation(
    SseDeserializer deserializer,
  );

  @protected
  ProtocolProfile
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtocolProfile(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AdminAction sse_decode_admin_action(SseDeserializer deserializer);

  @protected
  AdminConfigurationPatch sse_decode_admin_configuration_patch(
    SseDeserializer deserializer,
  );

  @protected
  AdminProgress sse_decode_admin_progress(SseDeserializer deserializer);

  @protected
  AdminReadOperation sse_decode_admin_read_operation(
    SseDeserializer deserializer,
  );

  @protected
  AdminResult sse_decode_admin_result(SseDeserializer deserializer);

  @protected
  AdminValueKind sse_decode_admin_value_kind(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BootstrapIdentityStep sse_decode_bootstrap_identity_step(
    SseDeserializer deserializer,
  );

  @protected
  CtapPinSession
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinSession(
    SseDeserializer deserializer,
  );

  @protected
  CtapPinToken
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinToken(
    SseDeserializer deserializer,
  );

  @protected
  ProtocolProfile
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtocolProfile(
    SseDeserializer deserializer,
  );

  @protected
  AdminConfigurationPatch sse_decode_box_autoadd_admin_configuration_patch(
    SseDeserializer deserializer,
  );

  @protected
  AdminProgress sse_decode_box_autoadd_admin_progress(
    SseDeserializer deserializer,
  );

  @protected
  AdminResult sse_decode_box_autoadd_admin_result(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  PivPrivateKeyData sse_decode_box_autoadd_piv_private_key_data(
    SseDeserializer deserializer,
  );

  @protected
  ProtocolError sse_decode_box_autoadd_protocol_error(
    SseDeserializer deserializer,
  );

  @protected
  SelfSignedCertificateParams
  sse_decode_box_autoadd_self_signed_certificate_params(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  X509CertData sse_decode_box_autoadd_x_509_cert_data(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  CtapPinSession?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinSession(
    SseDeserializer deserializer,
  );

  @protected
  CtapPinToken?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinToken(
    SseDeserializer deserializer,
  );

  @protected
  ProtocolProfile?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtocolProfile(
    SseDeserializer deserializer,
  );

  @protected
  AdminProgress? sse_decode_opt_box_autoadd_admin_progress(
    SseDeserializer deserializer,
  );

  @protected
  AdminResult? sse_decode_opt_box_autoadd_admin_result(
    SseDeserializer deserializer,
  );

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  PivPrivateKeyData? sse_decode_opt_box_autoadd_piv_private_key_data(
    SseDeserializer deserializer,
  );

  @protected
  ProtocolError? sse_decode_opt_box_autoadd_protocol_error(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  X509CertData? sse_decode_opt_box_autoadd_x_509_cert_data(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  PivCredentialOperation sse_decode_piv_credential_operation(
    SseDeserializer deserializer,
  );

  @protected
  PivImportFileData sse_decode_piv_import_file_data(
    SseDeserializer deserializer,
  );

  @protected
  PivPrivateKeyData sse_decode_piv_private_key_data(
    SseDeserializer deserializer,
  );

  @protected
  PivPublicKeyData sse_decode_piv_public_key_data(SseDeserializer deserializer);

  @protected
  PivReadOperation sse_decode_piv_read_operation(SseDeserializer deserializer);

  @protected
  ProtocolError sse_decode_protocol_error(SseDeserializer deserializer);

  @protected
  ProtocolStep sse_decode_protocol_step(SseDeserializer deserializer);

  @protected
  SelfSignedCertificateParams sse_decode_self_signed_certificate_params(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  X509CertData sse_decode_x_509_cert_data(SseDeserializer deserializer);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinSession(
    CtapPinSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinToken(
    CtapPinToken self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtocolOperation(
    ProtocolOperation self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtocolProfile(
    ProtocolProfile self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinSession(
    CtapPinSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinToken(
    CtapPinToken self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtocolOperation(
    ProtocolOperation self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtocolProfile(
    ProtocolProfile self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinSession(
    CtapPinSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinToken(
    CtapPinToken self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtocolProfile(
    ProtocolProfile self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinSession(
    CtapPinSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinToken(
    CtapPinToken self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtocolOperation(
    ProtocolOperation self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtocolProfile(
    ProtocolProfile self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_admin_action(AdminAction self, SseSerializer serializer);

  @protected
  void sse_encode_admin_configuration_patch(
    AdminConfigurationPatch self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_admin_progress(AdminProgress self, SseSerializer serializer);

  @protected
  void sse_encode_admin_read_operation(
    AdminReadOperation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_admin_result(AdminResult self, SseSerializer serializer);

  @protected
  void sse_encode_admin_value_kind(
    AdminValueKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_bootstrap_identity_step(
    BootstrapIdentityStep self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinSession(
    CtapPinSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinToken(
    CtapPinToken self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtocolProfile(
    ProtocolProfile self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_admin_configuration_patch(
    AdminConfigurationPatch self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_admin_progress(
    AdminProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_admin_result(
    AdminResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_piv_private_key_data(
    PivPrivateKeyData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_protocol_error(
    ProtocolError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_self_signed_certificate_params(
    SelfSignedCertificateParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_x_509_cert_data(
    X509CertData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinSession(
    CtapPinSession? self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinToken(
    CtapPinToken? self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtocolProfile(
    ProtocolProfile? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_admin_progress(
    AdminProgress? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_admin_result(
    AdminResult? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_piv_private_key_data(
    PivPrivateKeyData? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_protocol_error(
    ProtocolError? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_x_509_cert_data(
    X509CertData? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_piv_credential_operation(
    PivCredentialOperation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_piv_import_file_data(
    PivImportFileData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_piv_private_key_data(
    PivPrivateKeyData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_piv_public_key_data(
    PivPublicKeyData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_piv_read_operation(
    PivReadOperation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_protocol_error(ProtocolError self, SseSerializer serializer);

  @protected
  void sse_encode_protocol_step(ProtocolStep self, SseSerializer serializer);

  @protected
  void sse_encode_self_signed_certificate_params(
    SelfSignedCertificateParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_x_509_cert_data(X509CertData self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinSession(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinSession(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinSession(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinSession(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinToken(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinToken(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinToken(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinToken(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtocolOperation(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtocolOperation(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtocolOperation(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtocolOperation(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtocolProfile(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtocolProfile(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtocolProfile(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtocolProfile(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinSession(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinSession(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinToken(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCtapPinToken(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtocolOperation(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtocolOperation(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtocolProfile(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtocolProfile(
    int ptr,
  );
}
