// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/crypto.dart';
import 'api/decode.dart';
import 'api/piv_crypto.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 24609646;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'rust_lib_canokey_console',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  PivPublicKeyData crateApiPivCryptoBuildPivPublicKey(
      {required int algorithm,
      required List<int> cardData,
      required bool generatedResponse});

  String crateApiDecodeDecodePngQrcode({required List<int> pngFile});

  Uint8List crateApiCryptoEncryptPivManagementKeyChallenge(
      {required int algorithm,
      required List<int> key,
      required List<int> challenge});

  String crateApiPivCryptoFinishPivCsr(
      {required List<int> certificationRequestInfo,
      required int algorithm,
      required List<int> signature});

  Uint8List crateApiPivCryptoFinishSelfSignedCertificate(
      {required List<int> tbsCertificate,
      required int algorithm,
      required List<int> signature});

  Uint8List crateApiCryptoHmacSha1(
      {required List<int> key, required List<int> data});

  void crateApiInitApp();

  PivImportFileData crateApiPivCryptoParsePivImportFile(
      {required List<int> bytes});

  PivPublicKeyData crateApiPivCryptoParsePivPublicKeyInfo(
      {required int algorithm, required List<int> subjectPublicKeyInfo});

  X509CertData crateApiCryptoParseX509CertFromDer({required List<int> der});

  X509CertData crateApiCryptoParseX509CertFromPem({required String pem});

  Uint8List crateApiCryptoPbkdf2HmacSha1(
      {required String password,
      required List<int> salt,
      required int iterations,
      required int keyLen});

  Uint8List crateApiPivCryptoPreparePivCsr(
      {required String commonName,
      String? organization,
      String? organizationalUnit,
      String? country,
      required List<int> subjectPublicKeyInfo,
      required List<String> subjectAlternativeNames});

  Uint8List crateApiPivCryptoPreparePivSigningInput(
      {required int algorithm, required List<int> data, Uint8List? publicKey});

  Uint8List crateApiPivCryptoPrepareSelfSignedCertificate(
      {required SelfSignedCertificateParams params});

  Uint8List crateApiCryptoSha256Digest({required List<int> data});

  Uint8List crateApiCryptoSha384Digest({required List<int> data});

  Uint8List crateApiCryptoSha512Digest({required List<int> data});

  Uint8List crateApiCryptoSm2MessageDigest(
      {required List<int> data, required List<int> publicKey});

  Uint8List crateApiCryptoTdesEde3Enc(
      {required List<int> key, required List<int> data});

  bool crateApiCryptoVerifyPivSignature(
      {required int algorithm,
      required List<int> publicKey,
      required List<int> data,
      required List<int> signature});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  PivPublicKeyData crateApiPivCryptoBuildPivPublicKey(
      {required int algorithm,
      required List<int> cardData,
      required bool generatedResponse}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_u_8(algorithm, serializer);
        sse_encode_list_prim_u_8_loose(cardData, serializer);
        sse_encode_bool(generatedResponse, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_piv_public_key_data,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiPivCryptoBuildPivPublicKeyConstMeta,
      argValues: [algorithm, cardData, generatedResponse],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPivCryptoBuildPivPublicKeyConstMeta =>
      const TaskConstMeta(
        debugName: "build_piv_public_key",
        argNames: ["algorithm", "cardData", "generatedResponse"],
      );

  @override
  String crateApiDecodeDecodePngQrcode({required List<int> pngFile}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(pngFile, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDecodeDecodePngQrcodeConstMeta,
      argValues: [pngFile],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDecodeDecodePngQrcodeConstMeta =>
      const TaskConstMeta(
        debugName: "decode_png_qrcode",
        argNames: ["pngFile"],
      );

  @override
  Uint8List crateApiCryptoEncryptPivManagementKeyChallenge(
      {required int algorithm,
      required List<int> key,
      required List<int> challenge}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_u_8(algorithm, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        sse_encode_list_prim_u_8_loose(challenge, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiCryptoEncryptPivManagementKeyChallengeConstMeta,
      argValues: [algorithm, key, challenge],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoEncryptPivManagementKeyChallengeConstMeta =>
      const TaskConstMeta(
        debugName: "encrypt_piv_management_key_challenge",
        argNames: ["algorithm", "key", "challenge"],
      );

  @override
  String crateApiPivCryptoFinishPivCsr(
      {required List<int> certificationRequestInfo,
      required int algorithm,
      required List<int> signature}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(certificationRequestInfo, serializer);
        sse_encode_u_8(algorithm, serializer);
        sse_encode_list_prim_u_8_loose(signature, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiPivCryptoFinishPivCsrConstMeta,
      argValues: [certificationRequestInfo, algorithm, signature],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPivCryptoFinishPivCsrConstMeta =>
      const TaskConstMeta(
        debugName: "finish_piv_csr",
        argNames: ["certificationRequestInfo", "algorithm", "signature"],
      );

  @override
  Uint8List crateApiPivCryptoFinishSelfSignedCertificate(
      {required List<int> tbsCertificate,
      required int algorithm,
      required List<int> signature}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(tbsCertificate, serializer);
        sse_encode_u_8(algorithm, serializer);
        sse_encode_list_prim_u_8_loose(signature, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiPivCryptoFinishSelfSignedCertificateConstMeta,
      argValues: [tbsCertificate, algorithm, signature],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPivCryptoFinishSelfSignedCertificateConstMeta =>
      const TaskConstMeta(
        debugName: "finish_self_signed_certificate",
        argNames: ["tbsCertificate", "algorithm", "signature"],
      );

  @override
  Uint8List crateApiCryptoHmacSha1(
      {required List<int> key, required List<int> data}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(key, serializer);
        sse_encode_list_prim_u_8_loose(data, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCryptoHmacSha1ConstMeta,
      argValues: [key, data],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoHmacSha1ConstMeta => const TaskConstMeta(
        debugName: "hmac_sha1",
        argNames: ["key", "data"],
      );

  @override
  void crateApiInitApp() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInitAppConstMeta => const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  @override
  PivImportFileData crateApiPivCryptoParsePivImportFile(
      {required List<int> bytes}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(bytes, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_piv_import_file_data,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiPivCryptoParsePivImportFileConstMeta,
      argValues: [bytes],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPivCryptoParsePivImportFileConstMeta =>
      const TaskConstMeta(
        debugName: "parse_piv_import_file",
        argNames: ["bytes"],
      );

  @override
  PivPublicKeyData crateApiPivCryptoParsePivPublicKeyInfo(
      {required int algorithm, required List<int> subjectPublicKeyInfo}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_u_8(algorithm, serializer);
        sse_encode_list_prim_u_8_loose(subjectPublicKeyInfo, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_piv_public_key_data,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiPivCryptoParsePivPublicKeyInfoConstMeta,
      argValues: [algorithm, subjectPublicKeyInfo],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPivCryptoParsePivPublicKeyInfoConstMeta =>
      const TaskConstMeta(
        debugName: "parse_piv_public_key_info",
        argNames: ["algorithm", "subjectPublicKeyInfo"],
      );

  @override
  X509CertData crateApiCryptoParseX509CertFromDer({required List<int> der}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(der, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_x_509_cert_data,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiCryptoParseX509CertFromDerConstMeta,
      argValues: [der],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoParseX509CertFromDerConstMeta =>
      const TaskConstMeta(
        debugName: "parse_x509_cert_from_der",
        argNames: ["der"],
      );

  @override
  X509CertData crateApiCryptoParseX509CertFromPem({required String pem}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(pem, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_x_509_cert_data,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiCryptoParseX509CertFromPemConstMeta,
      argValues: [pem],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoParseX509CertFromPemConstMeta =>
      const TaskConstMeta(
        debugName: "parse_x509_cert_from_pem",
        argNames: ["pem"],
      );

  @override
  Uint8List crateApiCryptoPbkdf2HmacSha1(
      {required String password,
      required List<int> salt,
      required int iterations,
      required int keyLen}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(password, serializer);
        sse_encode_list_prim_u_8_loose(salt, serializer);
        sse_encode_u_32(iterations, serializer);
        sse_encode_u_32(keyLen, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCryptoPbkdf2HmacSha1ConstMeta,
      argValues: [password, salt, iterations, keyLen],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoPbkdf2HmacSha1ConstMeta =>
      const TaskConstMeta(
        debugName: "pbkdf2_hmac_sha1",
        argNames: ["password", "salt", "iterations", "keyLen"],
      );

  @override
  Uint8List crateApiPivCryptoPreparePivCsr(
      {required String commonName,
      String? organization,
      String? organizationalUnit,
      String? country,
      required List<int> subjectPublicKeyInfo,
      required List<String> subjectAlternativeNames}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(commonName, serializer);
        sse_encode_opt_String(organization, serializer);
        sse_encode_opt_String(organizationalUnit, serializer);
        sse_encode_opt_String(country, serializer);
        sse_encode_list_prim_u_8_loose(subjectPublicKeyInfo, serializer);
        sse_encode_list_String(subjectAlternativeNames, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiPivCryptoPreparePivCsrConstMeta,
      argValues: [
        commonName,
        organization,
        organizationalUnit,
        country,
        subjectPublicKeyInfo,
        subjectAlternativeNames
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPivCryptoPreparePivCsrConstMeta =>
      const TaskConstMeta(
        debugName: "prepare_piv_csr",
        argNames: [
          "commonName",
          "organization",
          "organizationalUnit",
          "country",
          "subjectPublicKeyInfo",
          "subjectAlternativeNames"
        ],
      );

  @override
  Uint8List crateApiPivCryptoPreparePivSigningInput(
      {required int algorithm, required List<int> data, Uint8List? publicKey}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_u_8(algorithm, serializer);
        sse_encode_list_prim_u_8_loose(data, serializer);
        sse_encode_opt_list_prim_u_8_strict(publicKey, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiPivCryptoPreparePivSigningInputConstMeta,
      argValues: [algorithm, data, publicKey],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPivCryptoPreparePivSigningInputConstMeta =>
      const TaskConstMeta(
        debugName: "prepare_piv_signing_input",
        argNames: ["algorithm", "data", "publicKey"],
      );

  @override
  Uint8List crateApiPivCryptoPrepareSelfSignedCertificate(
      {required SelfSignedCertificateParams params}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_self_signed_certificate_params(
            params, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiPivCryptoPrepareSelfSignedCertificateConstMeta,
      argValues: [params],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPivCryptoPrepareSelfSignedCertificateConstMeta =>
      const TaskConstMeta(
        debugName: "prepare_self_signed_certificate",
        argNames: ["params"],
      );

  @override
  Uint8List crateApiCryptoSha256Digest({required List<int> data}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(data, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCryptoSha256DigestConstMeta,
      argValues: [data],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoSha256DigestConstMeta => const TaskConstMeta(
        debugName: "sha256_digest",
        argNames: ["data"],
      );

  @override
  Uint8List crateApiCryptoSha384Digest({required List<int> data}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(data, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCryptoSha384DigestConstMeta,
      argValues: [data],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoSha384DigestConstMeta => const TaskConstMeta(
        debugName: "sha384_digest",
        argNames: ["data"],
      );

  @override
  Uint8List crateApiCryptoSha512Digest({required List<int> data}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(data, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCryptoSha512DigestConstMeta,
      argValues: [data],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoSha512DigestConstMeta => const TaskConstMeta(
        debugName: "sha512_digest",
        argNames: ["data"],
      );

  @override
  Uint8List crateApiCryptoSm2MessageDigest(
      {required List<int> data, required List<int> publicKey}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(data, serializer);
        sse_encode_list_prim_u_8_loose(publicKey, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiCryptoSm2MessageDigestConstMeta,
      argValues: [data, publicKey],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoSm2MessageDigestConstMeta =>
      const TaskConstMeta(
        debugName: "sm2_message_digest",
        argNames: ["data", "publicKey"],
      );

  @override
  Uint8List crateApiCryptoTdesEde3Enc(
      {required List<int> key, required List<int> data}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(key, serializer);
        sse_encode_list_prim_u_8_loose(data, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCryptoTdesEde3EncConstMeta,
      argValues: [key, data],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoTdesEde3EncConstMeta => const TaskConstMeta(
        debugName: "tdes_ede3_enc",
        argNames: ["key", "data"],
      );

  @override
  bool crateApiCryptoVerifyPivSignature(
      {required int algorithm,
      required List<int> publicKey,
      required List<int> data,
      required List<int> signature}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_u_8(algorithm, serializer);
        sse_encode_list_prim_u_8_loose(publicKey, serializer);
        sse_encode_list_prim_u_8_loose(data, serializer);
        sse_encode_list_prim_u_8_loose(signature, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCryptoVerifyPivSignatureConstMeta,
      argValues: [algorithm, publicKey, data, signature],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoVerifyPivSignatureConstMeta =>
      const TaskConstMeta(
        debugName: "verify_piv_signature",
        argNames: ["algorithm", "publicKey", "data", "signature"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PivPrivateKeyData dco_decode_box_autoadd_piv_private_key_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_piv_private_key_data(raw);
  }

  @protected
  SelfSignedCertificateParams
      dco_decode_box_autoadd_self_signed_certificate_params(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_self_signed_certificate_params(raw);
  }

  @protected
  X509CertData dco_decode_box_autoadd_x_509_cert_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_x_509_cert_data(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PivPrivateKeyData? dco_decode_opt_box_autoadd_piv_private_key_data(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_piv_private_key_data(raw);
  }

  @protected
  X509CertData? dco_decode_opt_box_autoadd_x_509_cert_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_x_509_cert_data(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  PivImportFileData dco_decode_piv_import_file_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return PivImportFileData(
      privateKey: dco_decode_opt_box_autoadd_piv_private_key_data(arr[0]),
      certificate: dco_decode_opt_box_autoadd_x_509_cert_data(arr[1]),
    );
  }

  @protected
  PivPrivateKeyData dco_decode_piv_private_key_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return PivPrivateKeyData(
      algorithm: dco_decode_u_8(arr[0]),
      importData: dco_decode_list_prim_u_8_strict(arr[1]),
      subjectPublicKeyInfo: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  PivPublicKeyData dco_decode_piv_public_key_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return PivPublicKeyData(
      subjectPublicKeyInfo: dco_decode_list_prim_u_8_strict(arr[0]),
      rawPublicKey: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  SelfSignedCertificateParams dco_decode_self_signed_certificate_params(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return SelfSignedCertificateParams(
      commonName: dco_decode_String(arr[0]),
      organization: dco_decode_opt_String(arr[1]),
      organizationalUnit: dco_decode_opt_String(arr[2]),
      country: dco_decode_opt_String(arr[3]),
      subjectPublicKeyInfo: dco_decode_list_prim_u_8_strict(arr[4]),
      serialNumber: dco_decode_list_prim_u_8_strict(arr[5]),
      notBefore: dco_decode_String(arr[6]),
      notAfter: dco_decode_String(arr[7]),
      subjectAlternativeNames: dco_decode_list_String(arr[8]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  X509CertData dco_decode_x_509_cert_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return X509CertData(
      bytes: dco_decode_list_prim_u_8_strict(arr[0]),
      subject: dco_decode_String(arr[1]),
      issuer: dco_decode_String(arr[2]),
      notBefore: dco_decode_String(arr[3]),
      notAfter: dco_decode_String(arr[4]),
      serialNumber: dco_decode_String(arr[5]),
      signatureAlgorithm: dco_decode_String(arr[6]),
      signatureValue: dco_decode_list_prim_u_8_strict(arr[7]),
      publicKeyAlgorithm: dco_decode_String(arr[8]),
      publicKeySize: dco_decode_usize(arr[9]),
      subjectPublicKeyInfo: dco_decode_list_prim_u_8_strict(arr[10]),
      rawPublicKey: dco_decode_list_prim_u_8_strict(arr[11]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  PivPrivateKeyData sse_decode_box_autoadd_piv_private_key_data(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_piv_private_key_data(deserializer));
  }

  @protected
  SelfSignedCertificateParams
      sse_decode_box_autoadd_self_signed_certificate_params(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_self_signed_certificate_params(deserializer));
  }

  @protected
  X509CertData sse_decode_box_autoadd_x_509_cert_data(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_x_509_cert_data(deserializer));
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PivPrivateKeyData? sse_decode_opt_box_autoadd_piv_private_key_data(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_piv_private_key_data(deserializer));
    } else {
      return null;
    }
  }

  @protected
  X509CertData? sse_decode_opt_box_autoadd_x_509_cert_data(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_x_509_cert_data(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PivImportFileData sse_decode_piv_import_file_data(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_privateKey =
        sse_decode_opt_box_autoadd_piv_private_key_data(deserializer);
    var var_certificate =
        sse_decode_opt_box_autoadd_x_509_cert_data(deserializer);
    return PivImportFileData(
        privateKey: var_privateKey, certificate: var_certificate);
  }

  @protected
  PivPrivateKeyData sse_decode_piv_private_key_data(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_algorithm = sse_decode_u_8(deserializer);
    var var_importData = sse_decode_list_prim_u_8_strict(deserializer);
    var var_subjectPublicKeyInfo =
        sse_decode_list_prim_u_8_strict(deserializer);
    return PivPrivateKeyData(
        algorithm: var_algorithm,
        importData: var_importData,
        subjectPublicKeyInfo: var_subjectPublicKeyInfo);
  }

  @protected
  PivPublicKeyData sse_decode_piv_public_key_data(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_subjectPublicKeyInfo =
        sse_decode_list_prim_u_8_strict(deserializer);
    var var_rawPublicKey = sse_decode_list_prim_u_8_strict(deserializer);
    return PivPublicKeyData(
        subjectPublicKeyInfo: var_subjectPublicKeyInfo,
        rawPublicKey: var_rawPublicKey);
  }

  @protected
  SelfSignedCertificateParams sse_decode_self_signed_certificate_params(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_commonName = sse_decode_String(deserializer);
    var var_organization = sse_decode_opt_String(deserializer);
    var var_organizationalUnit = sse_decode_opt_String(deserializer);
    var var_country = sse_decode_opt_String(deserializer);
    var var_subjectPublicKeyInfo =
        sse_decode_list_prim_u_8_strict(deserializer);
    var var_serialNumber = sse_decode_list_prim_u_8_strict(deserializer);
    var var_notBefore = sse_decode_String(deserializer);
    var var_notAfter = sse_decode_String(deserializer);
    var var_subjectAlternativeNames = sse_decode_list_String(deserializer);
    return SelfSignedCertificateParams(
        commonName: var_commonName,
        organization: var_organization,
        organizationalUnit: var_organizationalUnit,
        country: var_country,
        subjectPublicKeyInfo: var_subjectPublicKeyInfo,
        serialNumber: var_serialNumber,
        notBefore: var_notBefore,
        notAfter: var_notAfter,
        subjectAlternativeNames: var_subjectAlternativeNames);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  X509CertData sse_decode_x_509_cert_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_bytes = sse_decode_list_prim_u_8_strict(deserializer);
    var var_subject = sse_decode_String(deserializer);
    var var_issuer = sse_decode_String(deserializer);
    var var_notBefore = sse_decode_String(deserializer);
    var var_notAfter = sse_decode_String(deserializer);
    var var_serialNumber = sse_decode_String(deserializer);
    var var_signatureAlgorithm = sse_decode_String(deserializer);
    var var_signatureValue = sse_decode_list_prim_u_8_strict(deserializer);
    var var_publicKeyAlgorithm = sse_decode_String(deserializer);
    var var_publicKeySize = sse_decode_usize(deserializer);
    var var_subjectPublicKeyInfo =
        sse_decode_list_prim_u_8_strict(deserializer);
    var var_rawPublicKey = sse_decode_list_prim_u_8_strict(deserializer);
    return X509CertData(
        bytes: var_bytes,
        subject: var_subject,
        issuer: var_issuer,
        notBefore: var_notBefore,
        notAfter: var_notAfter,
        serialNumber: var_serialNumber,
        signatureAlgorithm: var_signatureAlgorithm,
        signatureValue: var_signatureValue,
        publicKeyAlgorithm: var_publicKeyAlgorithm,
        publicKeySize: var_publicKeySize,
        subjectPublicKeyInfo: var_subjectPublicKeyInfo,
        rawPublicKey: var_rawPublicKey);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_piv_private_key_data(
      PivPrivateKeyData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_piv_private_key_data(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_self_signed_certificate_params(
      SelfSignedCertificateParams self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_self_signed_certificate_params(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_x_509_cert_data(
      X509CertData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_x_509_cert_data(self, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_piv_private_key_data(
      PivPrivateKeyData? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_piv_private_key_data(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_x_509_cert_data(
      X509CertData? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_x_509_cert_data(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
      Uint8List? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_piv_import_file_data(
      PivImportFileData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_piv_private_key_data(
        self.privateKey, serializer);
    sse_encode_opt_box_autoadd_x_509_cert_data(self.certificate, serializer);
  }

  @protected
  void sse_encode_piv_private_key_data(
      PivPrivateKeyData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.algorithm, serializer);
    sse_encode_list_prim_u_8_strict(self.importData, serializer);
    sse_encode_list_prim_u_8_strict(self.subjectPublicKeyInfo, serializer);
  }

  @protected
  void sse_encode_piv_public_key_data(
      PivPublicKeyData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.subjectPublicKeyInfo, serializer);
    sse_encode_list_prim_u_8_strict(self.rawPublicKey, serializer);
  }

  @protected
  void sse_encode_self_signed_certificate_params(
      SelfSignedCertificateParams self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.commonName, serializer);
    sse_encode_opt_String(self.organization, serializer);
    sse_encode_opt_String(self.organizationalUnit, serializer);
    sse_encode_opt_String(self.country, serializer);
    sse_encode_list_prim_u_8_strict(self.subjectPublicKeyInfo, serializer);
    sse_encode_list_prim_u_8_strict(self.serialNumber, serializer);
    sse_encode_String(self.notBefore, serializer);
    sse_encode_String(self.notAfter, serializer);
    sse_encode_list_String(self.subjectAlternativeNames, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_x_509_cert_data(X509CertData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.bytes, serializer);
    sse_encode_String(self.subject, serializer);
    sse_encode_String(self.issuer, serializer);
    sse_encode_String(self.notBefore, serializer);
    sse_encode_String(self.notAfter, serializer);
    sse_encode_String(self.serialNumber, serializer);
    sse_encode_String(self.signatureAlgorithm, serializer);
    sse_encode_list_prim_u_8_strict(self.signatureValue, serializer);
    sse_encode_String(self.publicKeyAlgorithm, serializer);
    sse_encode_usize(self.publicKeySize, serializer);
    sse_encode_list_prim_u_8_strict(self.subjectPublicKeyInfo, serializer);
    sse_encode_list_prim_u_8_strict(self.rawPublicKey, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
