// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `copy_unsigned_integer`, `fixed_width_signature`, `gen_x590_meta`, `verify_ed25519_signature`, `verify_k256_signature`, `verify_p256_signature`, `verify_p384_signature`, `verify_p521_signature`, `verify_rsa_signature`, `verify_sm2_signature`, `x509_public_key_size`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DerSignature`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `decode_value`, `encode_value`, `value_len`

Uint8List tdesEde3Enc({required List<int> key, required List<int> data}) =>
    RustLib.instance.api.crateApiCryptoTdesEde3Enc(key: key, data: data);

Uint8List encryptPivManagementKeyChallenge(
        {required int algorithm,
        required List<int> key,
        required List<int> challenge}) =>
    RustLib.instance.api.crateApiCryptoEncryptPivManagementKeyChallenge(
        algorithm: algorithm, key: key, challenge: challenge);

Uint8List sha256Digest({required List<int> data}) =>
    RustLib.instance.api.crateApiCryptoSha256Digest(data: data);

Uint8List sha384Digest({required List<int> data}) =>
    RustLib.instance.api.crateApiCryptoSha384Digest(data: data);

Uint8List sha512Digest({required List<int> data}) =>
    RustLib.instance.api.crateApiCryptoSha512Digest(data: data);

Uint8List sm2MessageDigest(
        {required List<int> data, required List<int> publicKey}) =>
    RustLib.instance.api
        .crateApiCryptoSm2MessageDigest(data: data, publicKey: publicKey);

bool verifyPivSignature(
        {required int algorithm,
        required List<int> publicKey,
        required List<int> data,
        required List<int> signature}) =>
    RustLib.instance.api.crateApiCryptoVerifyPivSignature(
        algorithm: algorithm,
        publicKey: publicKey,
        data: data,
        signature: signature);

X509CertData parseX509CertFromPem({required String pem}) =>
    RustLib.instance.api.crateApiCryptoParseX509CertFromPem(pem: pem);

X509CertData parseX509CertFromDer({required List<int> der}) =>
    RustLib.instance.api.crateApiCryptoParseX509CertFromDer(der: der);

Uint8List pbkdf2HmacSha1(
        {required String password,
        required List<int> salt,
        required int iterations,
        required int keyLen}) =>
    RustLib.instance.api.crateApiCryptoPbkdf2HmacSha1(
        password: password, salt: salt, iterations: iterations, keyLen: keyLen);

Uint8List hmacSha1({required List<int> key, required List<int> data}) =>
    RustLib.instance.api.crateApiCryptoHmacSha1(key: key, data: data);

class X509CertData {
  final Uint8List bytes;
  final String subject;
  final String issuer;
  final String notBefore;
  final String notAfter;
  final String serialNumber;
  final String signatureAlgorithm;
  final Uint8List signatureValue;
  final String publicKeyAlgorithm;
  final BigInt publicKeySize;

  const X509CertData({
    required this.bytes,
    required this.subject,
    required this.issuer,
    required this.notBefore,
    required this.notAfter,
    required this.serialNumber,
    required this.signatureAlgorithm,
    required this.signatureValue,
    required this.publicKeyAlgorithm,
    required this.publicKeySize,
  });

  @override
  int get hashCode =>
      bytes.hashCode ^
      subject.hashCode ^
      issuer.hashCode ^
      notBefore.hashCode ^
      notAfter.hashCode ^
      serialNumber.hashCode ^
      signatureAlgorithm.hashCode ^
      signatureValue.hashCode ^
      publicKeyAlgorithm.hashCode ^
      publicKeySize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is X509CertData &&
          runtimeType == other.runtimeType &&
          bytes == other.bytes &&
          subject == other.subject &&
          issuer == other.issuer &&
          notBefore == other.notBefore &&
          notAfter == other.notAfter &&
          serialNumber == other.serialNumber &&
          signatureAlgorithm == other.signatureAlgorithm &&
          signatureValue == other.signatureValue &&
          publicKeyAlgorithm == other.publicKeyAlgorithm &&
          publicKeySize == other.publicKeySize;
}
