// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'crypto.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `algorithm_from_spki`, `der_error`, `ec_private_key_data`, `ed25519_private_key_data`, `encode_tlv_length`, `escape_dn_value`, `is_rsa`, `left_pad`, `normalize_signature`, `parse_ec_private_key_der`, `parse_ec_private_key_pem`, `parse_piv_pem_file`, `parse_private_key_der`, `parse_private_key_pem`, `pem_blocks`, `public_key_data`, `rsa_pkcs1_v15_input`, `rsa_private_key_data`, `signature_algorithm`, `subject_alt_name_extension`, `subject_name`, `tlv_value`, `validate_raw_public_key`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EcSignature`, `SignedDerObject`, `TbsCertificate`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `decode_value`, `decode_value`, `decode_value`, `encode_value`, `encode_value`, `encode_value`, `value_len`, `value_len`, `value_len`

PivPublicKeyData buildPivPublicKey(
        {required int algorithm,
        required List<int> cardData,
        required bool generatedResponse}) =>
    RustLib.instance.api.crateApiPivCryptoBuildPivPublicKey(
        algorithm: algorithm,
        cardData: cardData,
        generatedResponse: generatedResponse);

PivPublicKeyData parsePivPublicKeyInfo(
        {required int algorithm, required List<int> subjectPublicKeyInfo}) =>
    RustLib.instance.api.crateApiPivCryptoParsePivPublicKeyInfo(
        algorithm: algorithm, subjectPublicKeyInfo: subjectPublicKeyInfo);

PivImportFileData parsePivImportFile({required List<int> bytes}) =>
    RustLib.instance.api.crateApiPivCryptoParsePivImportFile(bytes: bytes);

Uint8List preparePivCsr(
        {required String commonName,
        String? organization,
        String? organizationalUnit,
        String? country,
        required List<int> subjectPublicKeyInfo,
        required List<String> subjectAlternativeNames}) =>
    RustLib.instance.api.crateApiPivCryptoPreparePivCsr(
        commonName: commonName,
        organization: organization,
        organizationalUnit: organizationalUnit,
        country: country,
        subjectPublicKeyInfo: subjectPublicKeyInfo,
        subjectAlternativeNames: subjectAlternativeNames);

String finishPivCsr(
        {required List<int> certificationRequestInfo,
        required int algorithm,
        required List<int> signature}) =>
    RustLib.instance.api.crateApiPivCryptoFinishPivCsr(
        certificationRequestInfo: certificationRequestInfo,
        algorithm: algorithm,
        signature: signature);

Uint8List prepareSelfSignedCertificate(
        {required SelfSignedCertificateParams params}) =>
    RustLib.instance.api
        .crateApiPivCryptoPrepareSelfSignedCertificate(params: params);

Uint8List finishSelfSignedCertificate(
        {required List<int> tbsCertificate,
        required int algorithm,
        required List<int> signature}) =>
    RustLib.instance.api.crateApiPivCryptoFinishSelfSignedCertificate(
        tbsCertificate: tbsCertificate,
        algorithm: algorithm,
        signature: signature);

Uint8List preparePivSigningInput(
        {required int algorithm,
        required List<int> data,
        Uint8List? publicKey}) =>
    RustLib.instance.api.crateApiPivCryptoPreparePivSigningInput(
        algorithm: algorithm, data: data, publicKey: publicKey);

class PivImportFileData {
  final PivPrivateKeyData? privateKey;
  final X509CertData? certificate;

  const PivImportFileData({
    this.privateKey,
    this.certificate,
  });

  @override
  int get hashCode => privateKey.hashCode ^ certificate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PivImportFileData &&
          runtimeType == other.runtimeType &&
          privateKey == other.privateKey &&
          certificate == other.certificate;
}

class PivPrivateKeyData {
  final int algorithm;

  /// PIV key component TLVs, excluding PIN and touch policy TLVs.
  final Uint8List importData;
  final Uint8List subjectPublicKeyInfo;

  const PivPrivateKeyData({
    required this.algorithm,
    required this.importData,
    required this.subjectPublicKeyInfo,
  });

  @override
  int get hashCode =>
      algorithm.hashCode ^ importData.hashCode ^ subjectPublicKeyInfo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PivPrivateKeyData &&
          runtimeType == other.runtimeType &&
          algorithm == other.algorithm &&
          importData == other.importData &&
          subjectPublicKeyInfo == other.subjectPublicKeyInfo;
}

class PivPublicKeyData {
  final Uint8List subjectPublicKeyInfo;
  final Uint8List rawPublicKey;

  const PivPublicKeyData({
    required this.subjectPublicKeyInfo,
    required this.rawPublicKey,
  });

  @override
  int get hashCode => subjectPublicKeyInfo.hashCode ^ rawPublicKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PivPublicKeyData &&
          runtimeType == other.runtimeType &&
          subjectPublicKeyInfo == other.subjectPublicKeyInfo &&
          rawPublicKey == other.rawPublicKey;
}

class SelfSignedCertificateParams {
  final String commonName;
  final String? organization;
  final String? organizationalUnit;
  final String? country;
  final Uint8List subjectPublicKeyInfo;
  final Uint8List serialNumber;
  final String notBefore;
  final String notAfter;
  final List<String> subjectAlternativeNames;

  const SelfSignedCertificateParams({
    required this.commonName,
    this.organization,
    this.organizationalUnit,
    this.country,
    required this.subjectPublicKeyInfo,
    required this.serialNumber,
    required this.notBefore,
    required this.notAfter,
    required this.subjectAlternativeNames,
  });

  @override
  int get hashCode =>
      commonName.hashCode ^
      organization.hashCode ^
      organizationalUnit.hashCode ^
      country.hashCode ^
      subjectPublicKeyInfo.hashCode ^
      serialNumber.hashCode ^
      notBefore.hashCode ^
      notAfter.hashCode ^
      subjectAlternativeNames.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SelfSignedCertificateParams &&
          runtimeType == other.runtimeType &&
          commonName == other.commonName &&
          organization == other.organization &&
          organizationalUnit == other.organizationalUnit &&
          country == other.country &&
          subjectPublicKeyInfo == other.subjectPublicKeyInfo &&
          serialNumber == other.serialNumber &&
          notBefore == other.notBefore &&
          notAfter == other.notAfter &&
          subjectAlternativeNames == other.subjectAlternativeNames;
}
