// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'piv_crypto.dart';

// These functions are ignored because they are not marked as `pub`: `bytes`, `drive`, `drive`, `failure`, `from_operation`, `operation`, `profile`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Inner`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CtapPinSession>>
abstract class CtapPinSession implements RustOpaqueInterface {
  /// Change the PIN (subcommand 0x04); IV handling matches [`Self::set_pin`].
  ProtocolOperation changePin({
    required List<int> oldPin,
    required List<int> newPin,
  });

  /// Idempotent local cleanup. Does not alter the card or pending operations.
  void close();

  /// Obtain a pinUvAuthToken with explicit permissions (subcommand 0x09):
  /// `permissions` is the raw bitfield (credentialManagement = 0x04) and
  /// `rp_id`, when present, binds the token to that relying party. The
  /// decrypted token is returned as an opaque handle in the final step.
  ProtocolOperation getPinTokenWithPermissions({
    required List<int> pin,
    required int permissions,
    String? rpId,
  });

  /// Set the initial PIN (subcommand 0x03). V2 IVs are generated here from
  /// the CSPRNG; PIN bytes enter upstream zeroizing owners immediately.
  ProtocolOperation setPin({required List<int> newPin});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CtapPinToken>>
abstract class CtapPinToken implements RustOpaqueInterface {
  /// Idempotent local cleanup. Does not alter the card or pending operations.
  void close();

  /// Permanently delete one resident credential by its raw credential ID
  /// (sent as a `public-key` descriptor). Never retried or rolled back;
  /// an unknown ID surfaces as NotFound (CTAP 0x2E/0x22).
  ProtocolOperation deleteCredential({required List<int> credentialId});

  /// Enumerate one RP's resident credentials. `metadata_only` enables the
  /// CanoKey vendor extension (subCommandParams key 0x80): the raw COSE
  /// algorithm replaces the public key in typed credential results.
  /// A Begin 0x2E yields an empty result.
  ProtocolOperation enumerateCredentials({
    required List<int> rpIdHash,
    required bool metadataOnly,
  });

  /// Enumerate relying parties with resident credentials (Begin + GetNext
  /// run inside the one operation). A 0x2E NO_CREDENTIALS status yields an
  /// empty result, not an error. Returns typed relying parties.
  ProtocolOperation enumerateRps();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ProtocolOperation>>
abstract class ProtocolOperation implements RustOpaqueInterface {
  /// Retained upstream progress, available even after protocol failure.
  AdminProgress? adminProgress();

  /// Consume one complete, unprocessed response including SW1/SW2.
  /// The input is copied into zeroizing storage and released before returning.
  ProtocolStep advance({required List<int> response});

  /// One raw bootstrap identity step for connection setup. The caller's
  /// exclusive lease spans SELECT and the serial read; a final non-9000
  /// status fails with the raw status word retained. No retry or replay.
  static ProtocolOperation bootstrapIdentity({
    required BootstrapIdentityStep step,
  }) => RustLib.instance.api.crateApiProtocolProtocolOperationBootstrapIdentity(
    step: step,
  );

  /// Release locally, including on a transport exception. Never retry/rollback.
  void close();

  /// Start ClientPIN key agreement (subcommand 0x02) for protocol version
  /// 1 or 2, generating the ephemeral P-256 scalar from the CSPRNG. The
  /// final step carries an opaque [`CtapPinSession`] handle.
  static ProtocolOperation ctapBeginPinSession({required int protocol}) =>
      RustLib.instance.api.crateApiProtocolProtocolOperationCtapBeginPinSession(
        protocol: protocol,
      );

  /// authenticatorGetInfo (0x04), profile-free with its own SELECT. The
  /// final `data` carries the parsed fields Dart needs (credMgmt/clientPin
  /// tri-states, forcePinChange, minPinLength, advertised pinUvAuthProtocol
  /// versions) as typed fields.
  static ProtocolOperation ctapGetInfo() =>
      RustLib.instance.api.crateApiProtocolProtocolOperationCtapGetInfo();

  /// Profile-free NDEF capability-container read. Selects the NDEF applet.
  /// Returns the maximum message length (excluding NLEN) and write protection.
  static ProtocolOperation ndefReadCapability() => RustLib.instance.api
      .crateApiProtocolProtocolOperationNdefReadCapability();

  /// Profile-free full NDEF message read; chunked by the upstream machine.
  /// Data is the raw message without the two NLEN bytes.
  static ProtocolOperation ndefReadMessage() =>
      RustLib.instance.api.crateApiProtocolProtocolOperationNdefReadMessage();

  /// Crash-safe NDEF message replacement: zero NLEN, message chunks, real
  /// NLEN. A failed mid-write leaves no stale message and is never replayed.
  static ProtocolOperation ndefWriteMessage({required List<int> message}) =>
      RustLib.instance.api.crateApiProtocolProtocolOperationNdefWriteMessage(
        message: message,
      );

  /// Construct without I/O. Reads never probe, SELECT, authenticate, or
  /// retain a device profile implicitly.
  static ProtocolOperation pivRead({required PivReadOperation kind}) =>
      RustLib.instance.api.crateApiProtocolProtocolOperationPivRead(kind: kind);

  /// Admin-only discovery before authentication; does not select PIV. A
  /// four-byte serial already observed by the connection bootstrap is
  /// recorded as the probe observation and the serial read is skipped.
  static ProtocolOperation probeAdmin({Uint8List? observedSerial}) =>
      RustLib.instance.api.crateApiProtocolProtocolOperationProbeAdmin(
        observedSerial: observedSerial,
      );

  /// Explicit Admin/PIV discovery. Call before authentication in the same
  /// exclusive lease; the completed profile is transferred to Dart exactly once.
  /// A bootstrap-observed serial skips the duplicate serial read.
  static ProtocolOperation probePiv({Uint8List? observedSerial}) =>
      RustLib.instance.api.crateApiProtocolProtocolOperationProbePiv(
        observedSerial: observedSerial,
      );

  /// Start exactly once; subsequent calls report an operation-state error.
  ProtocolStep start();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ProtocolProfile>>
abstract class ProtocolProfile implements RustOpaqueInterface {
  ProtocolOperation adminAction({
    required AdminAction kind,
    Uint8List? pin,
    required List<int> data,
    required int index,
    required int value,
    required bool existing,
  });

  /// `existing` reuses the caller's authorized Admin transaction and forbids
  /// a PIN; otherwise the operation SELECTs and verifies the supplied PIN.
  ProtocolOperation adminConfigure({
    required AdminConfigurationPatch patch,
    Uint8List? pin,
    required bool existing,
  });

  /// Read both typed PASS slot configurations (INS 43). `existing` reuses the
  /// caller's selected, already authorized Admin transaction and forbids a
  /// PIN; otherwise the operation SELECTs and verifies the supplied PIN.
  /// Secret slot material is never returned by firmware.
  ProtocolOperation adminPassSlots({Uint8List? pin, required bool existing});

  /// `existing` reuses the caller's selected, already authorized Admin
  /// transaction and forbids a PIN; otherwise the operation SELECTs and
  /// verifies only an explicitly supplied PIN.
  ProtocolOperation adminRead({
    required AdminReadOperation kind,
    Uint8List? pin,
    required bool existing,
  });

  /// Replace one PASS slot (INS 44): slot 0 = short touch, 1 = long touch;
  /// kind 0 = off, 1 = static password (data, append_enter), 2 = HMAC-SHA1
  /// (data = 20-byte key). OATH slots are configured through the OATH
  /// applet, never here. The write is validated before any I/O.
  ProtocolOperation adminSetPassSlot({
    required int slot,
    required int kind,
    required List<int> data,
    required bool appendEnter,
    Uint8List? pin,
    required bool existing,
  });

  /// Idempotent local cleanup. Does not alter the card or already-created ops.
  void close();

  /// Bootstrap observations, not an authenticated session or cached credential.
  Uint8List? firmware();

  String? model();

  ProtocolOperation oathCalculate({
    required List<int> name,
    required int kind,
    required int algorithm,
    Uint8List? challenge,
    required int format,
    Uint8List? accessKey,
    Uint8List? accessChallenge,
  });

  ProtocolOperation oathCalculateAll({
    required List<int> challenge,
    required int format,
    Uint8List? accessKey,
    Uint8List? accessChallenge,
  });

  ProtocolOperation oathClearCode({Uint8List? key, Uint8List? challenge});

  ProtocolOperation oathDelete({
    required List<int> name,
    Uint8List? accessKey,
    Uint8List? accessChallenge,
  });

  ProtocolOperation oathPut({
    required List<int> name,
    required int kind,
    required int algorithm,
    required int digits,
    required List<int> secret,
    required bool requireTouch,
    required bool increasing,
    required int initialCounter,
    Uint8List? accessKey,
    Uint8List? accessChallenge,
  });

  ProtocolOperation oathSelect();

  /// The current key validates in the same operation only when supplied;
  /// setting the first code on an unprotected applet passes no old key.
  ProtocolOperation oathSetCode({
    Uint8List? oldKey,
    required List<int> newKey,
    required List<int> challenge,
  });

  /// Mark an existing HOTP credential as the touch keyboard-emulation
  /// default: slot 0 = short, 1 = long. The legacy (pre-3.0) single-slot
  /// dialect is chosen from the probed profile; a long slot or append-enter
  /// there fails construction with InvalidArgument before any I/O.
  ProtocolOperation oathSetDefault({
    required int slot,
    required bool appendEnter,
    required String name,
    Uint8List? accessKey,
    Uint8List? accessChallenge,
  });

  ProtocolOperation oathValidate({
    required List<int> key,
    required List<int> challenge,
  });

  ProtocolOperation openpgpChangePassword({
    required int reference,
    required List<int> old,
    required List<int> new_,
  });

  ProtocolOperation openpgpReadData({required int tag});

  /// Set PW1/reset-code/PW3 retry limits after explicit PW3 verification.
  /// The card resets PW1/PW3 to firmware defaults and clears authorization;
  /// the retry-reset capability gates construction before any I/O.
  ProtocolOperation openpgpResetRetries({
    required List<int> retries,
    required List<int> password,
  });

  /// Reset PW1 after explicit PW3 verification; does not change PW3.
  ProtocolOperation openpgpUnblockWithAdmin({
    required List<int> newPin,
    required List<int> password,
  });

  /// Reset PW1 using reset-code||new-PW1; no password verification is inserted.
  ProtocolOperation openpgpUnblockWithCode({
    required List<int> code,
    required List<int> newPin,
  });

  ProtocolOperation openpgpVerify({
    required int reference,
    required List<int> password,
  });

  /// Set (Some) or clear (None) the reset code after explicit PW3 verification.
  ProtocolOperation openpgpWriteResetCode({
    Uint8List? resetCode,
    required List<int> password,
  });

  /// Whether one explicit PW1-sign verification may authorize multiple
  /// signatures (PW status bytes policy). Written after PW3 verification.
  ProtocolOperation openpgpWriteSignaturePinPolicy({
    required bool reuse,
    required List<int> password,
  });

  /// Touch cache duration in seconds after PW3 verification; UIF-gated.
  ProtocolOperation openpgpWriteTouchCacheTime({
    required int seconds,
    required List<int> password,
  });

  /// Slot touch policy (0 off, 1 on, 2 permanent) after PW3 verification.
  /// Emits the standard two-byte UIF field; the UIF capability gates it.
  ProtocolOperation openpgpWriteTouchPolicy({
    required int slot,
    required int policy,
    required List<int> password,
  });

  /// Resolve an observed key algorithm to Console's fixed display enum IDs.
  /// These are NOT device wire IDs and never authorize a key operation.
  /// Unknown algorithms and closed profiles return None.
  int? pivAlgorithmDisplayId({required int wireId});

  /// INS F9 attestation certificate for a generated slot. The selected-context
  /// factory asserts no credential and consumes no authentication state.
  ProtocolOperation pivAttest({required int slot});

  /// Preserve Console's explicit external authentication mode. libcanokey owns
  /// the full challenge exchange and cryptography; no host login is inferred.
  ProtocolOperation pivAuthenticateManagement({
    required int algorithm,
    required List<int> key,
  });

  /// Reuse the caller's selected transaction; the profile is evidence only.
  ProtocolOperation pivCertificate({required int objectId});

  /// Credentials are copied into upstream zeroizing owners before returning.
  /// Success does not turn this immutable profile into an authorization token.
  ProtocolOperation pivCredential({
    required PivCredentialOperation kind,
    required List<int> current,
    required List<int> replacement,
  });

  ProtocolOperation pivDecapsulate({
    required int slot,
    required List<int> ciphertext,
  });

  ProtocolOperation pivDeleteKey({required int slot});

  ProtocolOperation pivDerive({
    required int slot,
    required int algorithm,
    required List<int> peer,
  });

  ProtocolOperation pivGenerateKey({
    required int slot,
    required int algorithm,
    required int pinPolicy,
    required int touchPolicy,
  });

  /// Import a post-quantum seed (INS FE): kind 0 = ML-DSA-65 (32-byte seed),
  /// 1 = ML-KEM-768 (64-byte d||z seed). Semantics match the EC/RSA/Ed25519
  /// imports: Access::Existing inside the caller's reserved transaction.
  ProtocolOperation pivImportPqSeed({
    required int slot,
    required int kind,
    required List<int> seed,
    required int pinPolicy,
    required int touchPolicy,
  });

  /// Import validated file material without round-tripping private components through Dart.
  ProtocolOperation pivImportPrivateKey({
    required int slot,
    required int algorithm,
    required PivPrivateKeyData key,
    required int pinPolicy,
    required int touchPolicy,
  });

  /// Read metadata in the caller's already selected PIV session. No probing,
  /// SELECT or authentication is inserted, including after VERIFY.
  ProtocolOperation pivMetadata({required int reference});

  /// Read the PIV metadata directory in the caller's selected transaction.
  /// The upstream parser validates framing and preserves the raw directory.
  ProtocolOperation pivMetadataDirectory();

  ProtocolOperation pivMoveKey({required int source, required int target});

  /// Read the PIV algorithm extension configuration (INS EE). Without a
  /// management key this reuses the caller's selected transaction
  /// (`Access::Existing`); with one, upstream SELECTs, authenticates
  /// (external GENERAL AUTHENTICATE) and reads within the same operation.
  /// On 3.0.x firmware (`PivProtectedAlgorithmConfigRead`) an
  /// unauthenticated read is rejected with SecurityStatusNotSatisfied; on
  /// firmware without the read the capability check fails at construction,
  /// before any authentication I/O.
  ProtocolOperation pivReadAlgorithmConfig({
    Uint8List? managementKey,
    required int managementKeyAlgorithm,
  });

  /// Return the normalized object value. libcanokey owns framing and parsing.
  ProtocolOperation pivReadObject({required List<int> objectId});

  ProtocolOperation pivResetPinPukRetries({
    required int pinRetries,
    required int pukRetries,
  });

  ProtocolOperation pivSetAlgorithmConfig({required List<int> raw});

  ProtocolOperation pivSetManagementKey({
    required int algorithm,
    required List<int> key,
    required int touch,
    required bool updateProtected,
  });

  ProtocolOperation pivSign({
    required int slot,
    required int algorithm,
    required List<int> input,
    required int inputKind,
  });

  /// Firmware streaming signature modes: 0 = ML-DSA-65 with the empty context,
  /// 1 = randomized Ed25519 (wire mode FF), 2 = SM2 full message with an
  /// optional user ID. Classic digest/padded signing stays with `piv_sign`.
  ProtocolOperation pivSignStreaming({
    required int slot,
    required int mode,
    required List<int> message,
    Uint8List? userId,
  });

  /// Writes may be partially applied before failure; never retry or roll back.
  /// Existing delegates authorization to the card in the caller-owned lease.
  ProtocolOperation pivWriteObject({
    required List<int> objectId,
    required List<int> data,
  });

  /// The serial observed during explicit discovery. Missing observations stay absent.
  Uint8List? serial();
}

enum AdminAction {
  verifyPin,
  changePin,
  keyboardInterface,
  keyboardReturn,
  keyboardKeymap,
  clearKeyboardKeymap,
  legacyTouch,
  writeSm2,
  nfc,
  resetOpenPgp,
  resetPiv,
  resetOath,
  resetNdef,
  resetCtap,
  resetPass,
  factoryReset,
}

class AdminAppletUsage {
  final int appletId;
  final int flags;
  final int logicalBytes;

  const AdminAppletUsage({
    required this.appletId,
    required this.flags,
    required this.logicalBytes,
  });

  @override
  int get hashCode =>
      appletId.hashCode ^ flags.hashCode ^ logicalBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AdminAppletUsage &&
          runtimeType == other.runtimeType &&
          appletId == other.appletId &&
          flags == other.flags &&
          logicalBytes == other.logicalBytes;
}

class AdminConfigurationPatch {
  final bool? ledOn;
  final bool? ndefReadOnly;
  final bool? ndefEnabled;
  final bool? webusbLanding;
  final int featureMask;
  final int featureValues;

  const AdminConfigurationPatch({
    this.ledOn,
    this.ndefReadOnly,
    this.ndefEnabled,
    this.webusbLanding,
    required this.featureMask,
    required this.featureValues,
  });

  @override
  int get hashCode =>
      ledOn.hashCode ^
      ndefReadOnly.hashCode ^
      ndefEnabled.hashCode ^
      webusbLanding.hashCode ^
      featureMask.hashCode ^
      featureValues.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AdminConfigurationPatch &&
          runtimeType == other.runtimeType &&
          ledOn == other.ledOn &&
          ndefReadOnly == other.ndefReadOnly &&
          ndefEnabled == other.ndefEnabled &&
          webusbLanding == other.webusbLanding &&
          featureMask == other.featureMask &&
          featureValues == other.featureValues;
}

/// Copy progress before close, including on transport failure or cancellation.
class AdminProgress {
  final int confirmedWrites;
  final bool reprobeRequired;

  const AdminProgress({
    required this.confirmedWrites,
    required this.reprobeRequired,
  });

  @override
  int get hashCode => confirmedWrites.hashCode ^ reprobeRequired.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AdminProgress &&
          runtimeType == other.runtimeType &&
          confirmedWrites == other.confirmedWrites &&
          reprobeRequired == other.reprobeRequired;
}

/// Admin operations always SELECT, then verify only an explicitly supplied PIN.
enum AdminReadOperation {
  firmware,
  model,
  serial,
  chipId,
  coreCommit,
  configuration,
  flashUsage,
  appletUsage,
  keyboardLayout,
  keyboardKeymap,
  nfcStatus,
  sm2Configuration,
}

class AdminResult {
  final AdminValueKind kind;
  final Uint8List data;
  final AdminProgress progress;
  final List<PassSlotData>? passSlots;
  final AdminStorageUsage? flashUsage;
  final List<AdminAppletUsage>? appletUsage;

  const AdminResult({
    required this.kind,
    required this.data,
    required this.progress,
    this.passSlots,
    this.flashUsage,
    this.appletUsage,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      data.hashCode ^
      progress.hashCode ^
      passSlots.hashCode ^
      flashUsage.hashCode ^
      appletUsage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AdminResult &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          data == other.data &&
          progress == other.progress &&
          passSlots == other.passSlots &&
          flashUsage == other.flashUsage &&
          appletUsage == other.appletUsage;
}

class AdminStorageUsage {
  final int usedKiB;
  final int totalKiB;

  const AdminStorageUsage({required this.usedKiB, required this.totalKiB});

  @override
  int get hashCode => usedKiB.hashCode ^ totalKiB.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AdminStorageUsage &&
          runtimeType == other.runtimeType &&
          usedKiB == other.usedKiB &&
          totalKiB == other.totalKiB;
}

enum AdminValueKind {
  none,
  bytes,
  configuration,
  legacyConfiguration,
  flashUsage,
  appletUsage,
  nfcStatus,
  sm2Configuration,
  legacySm2Configuration,
  pinStatus,
  keyboardLayout,
  keyboardKeymap,
  passSlots,
}

/// Connection-bootstrap identity steps; raw Admin commands without a profile.
/// Upstream builders own encoding and safe Le correction; no authentication,
/// no other applet selection and no device observations are created.
enum BootstrapIdentityStep { selectAdmin, serial }

class CtapCredential {
  final Uint8List credentialId;
  final Uint8List? userId;
  final String? userName;
  final String? userDisplayName;
  final int? credProtect;
  final PlatformInt64? coseAlgorithm;
  final Uint8List? publicKey;

  const CtapCredential({
    required this.credentialId,
    this.userId,
    this.userName,
    this.userDisplayName,
    this.credProtect,
    this.coseAlgorithm,
    this.publicKey,
  });

  @override
  int get hashCode =>
      credentialId.hashCode ^
      userId.hashCode ^
      userName.hashCode ^
      userDisplayName.hashCode ^
      credProtect.hashCode ^
      coseAlgorithm.hashCode ^
      publicKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CtapCredential &&
          runtimeType == other.runtimeType &&
          credentialId == other.credentialId &&
          userId == other.userId &&
          userName == other.userName &&
          userDisplayName == other.userDisplayName &&
          credProtect == other.credProtect &&
          coseAlgorithm == other.coseAlgorithm &&
          publicKey == other.publicKey;
}

class CtapInfo {
  final bool? credMgmt;
  final bool? clientPin;
  final bool? forcePinChange;
  final BigInt? minPinLength;
  final Uint8List pinUvAuthProtocols;

  const CtapInfo({
    this.credMgmt,
    this.clientPin,
    this.forcePinChange,
    this.minPinLength,
    required this.pinUvAuthProtocols,
  });

  @override
  int get hashCode =>
      credMgmt.hashCode ^
      clientPin.hashCode ^
      forcePinChange.hashCode ^
      minPinLength.hashCode ^
      pinUvAuthProtocols.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CtapInfo &&
          runtimeType == other.runtimeType &&
          credMgmt == other.credMgmt &&
          clientPin == other.clientPin &&
          forcePinChange == other.forcePinChange &&
          minPinLength == other.minPinLength &&
          pinUvAuthProtocols == other.pinUvAuthProtocols;
}

class CtapRp {
  final String id;
  final String? name;
  final Uint8List idHash;

  const CtapRp({required this.id, this.name, required this.idHash});

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ idHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CtapRp &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          idHash == other.idHash;
}

class NdefCapabilityData {
  final int maxMessageLength;
  final bool readOnly;

  const NdefCapabilityData({
    required this.maxMessageLength,
    required this.readOnly,
  });

  @override
  int get hashCode => maxMessageLength.hashCode ^ readOnly.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NdefCapabilityData &&
          runtimeType == other.runtimeType &&
          maxMessageLength == other.maxMessageLength &&
          readOnly == other.readOnly;
}

class OathCalculation {
  final Uint8List? name;
  final int digits;
  final OathCode code;
  final int? rawCode;
  final Uint8List? fullCode;

  const OathCalculation({
    this.name,
    required this.digits,
    required this.code,
    this.rawCode,
    this.fullCode,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      digits.hashCode ^
      code.hashCode ^
      rawCode.hashCode ^
      fullCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OathCalculation &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          digits == other.digits &&
          code == other.code &&
          rawCode == other.rawCode &&
          fullCode == other.fullCode;
}

enum OathCode { truncated, full, hotp, touchRequired }

/// OATH selection evidence, including legacy serial observations.
class OathSelectionData {
  final Uint8List? version;
  final Uint8List? salt;
  final Uint8List? challenge;
  final Uint8List? serial;

  const OathSelectionData({
    this.version,
    this.salt,
    this.challenge,
    this.serial,
  });

  @override
  int get hashCode =>
      version.hashCode ^ salt.hashCode ^ challenge.hashCode ^ serial.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OathSelectionData &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          salt == other.salt &&
          challenge == other.challenge &&
          serial == other.serial;
}

class PassSlotData {
  final int kind;
  final Uint8List name;
  final bool appendEnter;

  const PassSlotData({
    required this.kind,
    required this.name,
    required this.appendEnter,
  });

  @override
  int get hashCode => kind.hashCode ^ name.hashCode ^ appendEnter.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PassSlotData &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          name == other.name &&
          appendEnter == other.appendEnter;
}

/// Explicit actions in an already prepared lease; never SELECT or probe.
enum PivCredentialOperation { verifyPin, changePin, changePuk, unblockPin }

/// Initial PIV operations; reads require an already selected PIV application.
enum PivReadOperation { pinStatus }

/// Structured, payload-free protocol failure. Transport errors remain in Dart.
/// For CTAP-level failures `status_word` carries the raw CTAP status byte
/// widened to u16 (for example 0x0031 for PIN_INVALID), NOT an ISO 7816
/// status word; see canokey-ctap's status table. Upstream keeps that byte in
/// `Error::application_status` (`status_word` is ISO-only); the bridge maps it
/// here so the Dart contract is unchanged.
class ProtocolError {
  final String kind;
  final String phase;
  final int? statusWord;
  final String? reference;
  final int? retriesRemaining;

  const ProtocolError({
    required this.kind,
    required this.phase,
    this.statusWord,
    this.reference,
    this.retriesRemaining,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      phase.hashCode ^
      statusWord.hashCode ^
      reference.hashCode ^
      retriesRemaining.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProtocolError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          phase == other.phase &&
          statusWord == other.statusWord &&
          reference == other.reference &&
          retriesRemaining == other.retriesRemaining;
}

/// Exactly one field is present: exchange a command, consume a result, or fail.
/// Command and result copies belong to Dart; getters never perform I/O.
class ProtocolStep {
  final Uint8List? command;
  final Uint8List? data;
  final ProtocolError? error;
  final ProtocolProfile? profile;
  final AdminResult? admin;
  final CtapPinSession? pinSession;
  final CtapPinToken? pinToken;
  final OathSelectionData? oathSelection;
  final List<OathCalculation>? oathCalculations;
  final CtapInfo? ctapInfo;
  final NdefCapabilityData? ndefCapability;
  final List<CtapRp>? ctapRps;
  final List<CtapCredential>? ctapCredentials;

  const ProtocolStep({
    this.command,
    this.data,
    this.error,
    this.profile,
    this.admin,
    this.pinSession,
    this.pinToken,
    this.oathSelection,
    this.oathCalculations,
    this.ctapInfo,
    this.ndefCapability,
    this.ctapRps,
    this.ctapCredentials,
  });

  static ProtocolStep default_() =>
      RustLib.instance.api.crateApiProtocolProtocolStepDefault();

  @override
  int get hashCode =>
      command.hashCode ^
      data.hashCode ^
      error.hashCode ^
      profile.hashCode ^
      admin.hashCode ^
      pinSession.hashCode ^
      pinToken.hashCode ^
      oathSelection.hashCode ^
      oathCalculations.hashCode ^
      ctapInfo.hashCode ^
      ndefCapability.hashCode ^
      ctapRps.hashCode ^
      ctapCredentials.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProtocolStep &&
          runtimeType == other.runtimeType &&
          command == other.command &&
          data == other.data &&
          error == other.error &&
          profile == other.profile &&
          admin == other.admin &&
          pinSession == other.pinSession &&
          pinToken == other.pinToken &&
          oathSelection == other.oathSelection &&
          oathCalculations == other.oathCalculations &&
          ctapInfo == other.ctapInfo &&
          ndefCapability == other.ndefCapability &&
          ctapRps == other.ctapRps &&
          ctapCredentials == other.ctapCredentials;
}
