// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `drive`, `drive`, `failure`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Inner`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ProtocolOperation>>
abstract class ProtocolOperation implements RustOpaqueInterface {
  /// Consume one complete, unprocessed response including SW1/SW2.
  /// The input is copied into zeroizing storage and released before returning.
  ProtocolStep advance({required List<int> response});

  /// Release locally, including on a transport exception. Never retry/rollback.
  void close();

  /// Construct without I/O. Only Select changes applet selection; reads never
  /// probe, SELECT, authenticate, or retain a device profile implicitly.
  static ProtocolOperation pivRead({required PivReadOperation kind}) =>
      RustLib.instance.api.crateApiProtocolProtocolOperationPivRead(kind: kind);

  /// Start exactly once; subsequent calls report an operation-state error.
  ProtocolStep start();
}

/// Initial PIV operations; reads require an already selected PIV application.
enum PivReadOperation { select, version, algorithmConfiguration }

/// Structured, payload-free protocol failure. Transport errors remain in Dart.
class ProtocolError {
  final String kind;
  final String phase;
  final int? statusWord;
  final String? reference;
  final int? retriesRemaining;

  const ProtocolError({
    required this.kind,
    required this.phase,
    this.statusWord,
    this.reference,
    this.retriesRemaining,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      phase.hashCode ^
      statusWord.hashCode ^
      reference.hashCode ^
      retriesRemaining.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProtocolError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          phase == other.phase &&
          statusWord == other.statusWord &&
          reference == other.reference &&
          retriesRemaining == other.retriesRemaining;
}

/// Exactly one field is present: exchange a command, consume a result, or fail.
/// Command and result copies belong to Dart; getters never perform I/O.
class ProtocolStep {
  final Uint8List? command;
  final Uint8List? data;
  final ProtocolError? error;

  const ProtocolStep({this.command, this.data, this.error});

  @override
  int get hashCode => command.hashCode ^ data.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProtocolStep &&
          runtimeType == other.runtimeType &&
          command == other.command &&
          data == other.data &&
          error == other.error;
}
