name: Build Apps

on:
  push:
    branches: [main, develop, ci]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  JAVA_VERSION: 17
  FLUTTER_VERSION: 3.47.1
  RUST_VERSION: 1.98.1

jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: apk
            job-name: apk-release
            artifact-name: canokey-console-apk-release
            os: ubuntu-latest
            pre-build-script: |
              sed -i 's/signingConfigs.release/signingConfigs.debug/' android/app/build.gradle
            build-args: ""
            artifact-path: build/app/outputs/flutter-apk/app-release.apk
          - target: linux
            arch: amd64
            job-name: linux-amd64-release
            artifact-name: canokey-console-linux-amd64-release
            os: ubuntu-24.04
            pre-build-script: |
              sudo apt-get update -y
              sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev # flutter dependencies
              sudo apt-get install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev # audioplayers_linux dependencies
              sudo apt-get install -y libcurl4-openssl-dev # see https://github.com/getsentry/sentry-dart/issues/2504
              sudo snap install snapcraft --classic
            build-args: ""
            artifact-path: build/linux/*.snap
          - target: linux
            arch: arm64
            job-name: linux-arm64-release
            artifact-name: canokey-console-linux-arm64-release
            os: ubuntu-24.04-arm
            pre-build-script: |
              sudo apt-get update -y
              sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev # flutter dependencies
              sudo apt-get install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev # audioplayers_linux dependencies
              sudo apt-get install -y libcurl4-openssl-dev # see https://github.com/getsentry/sentry-dart/issues/2504
              sudo snap install snapcraft --classic
            build-args: ""
            artifact-path: build/linux/*.snap
          - target: windows
            job-name: windows-release
            artifact-name: canokey-console-windows-release
            os: windows-latest
            pre-build-script: ""
            build-args: ""
            artifact-path: build/windows/x64/runner/Release
          - target: macos
            job-name: macos-release
            artifact-name: canokey-console-macos-release
            os: macos-latest
            pre-build-script: ""
            build-args: ""
            artifact-path: build/macos/Build/Products/Release/*.app
          - target: ios
            job-name: ios-release
            artifact-name: canokey-console-ios-release
            os: macos-26
            pre-build-script: ""
            build-args: "--no-codesign"
            artifact-path: |
              build/ios/iphoneos/Runner.app

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.job-name }}

    steps:

    # setup environment
    - uses: actions/checkout@v6
    - uses: actions/cache@v5
      with:
        key: apk-${{ hashFiles('rust/Cargo.toml') }}
        path: |
          ~/.gradle
          rust/target

    # setup dependencies
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ env.RUST_VERSION }}
        components: rust-src
    - uses: actions/setup-java@v5
      if: ${{ matrix.target == 'apk' || matrix.target == 'linux' }}
      with:
        distribution: 'temurin'
        java-version: ${{ env.JAVA_VERSION }}
    - name: Setup Flutter SDK
      uses: flutter-actions/setup-flutter@v4
      with:
        channel: stable
        version: ${{ env.FLUTTER_VERSION }}
        cache: true
    - name: pre-build-script script for ${{ matrix.target }}
      run: ${{ matrix.pre-build-script }}

    # basic format & linting check
    - run: flutter pub get
    # - run: dart format --output=none --set-exit-if-changed lib/
    - run: dart analyze

    # build flutter app
    - name: Install Flutter Rust Bridge
      run: cargo install flutter_rust_bridge_codegen --version 2.13.0 --locked
    - name: Run flutter release build (${{ matrix.target }})
      run: |
        flutter build ${{ matrix.target }} --release ${{ matrix.build-args }} --verbose
        if [ "${{ matrix.target }}" == "linux" ]; then
          sudo sh -c 'umask 022; exec /snap/bin/snapcraft pack --destructive-mode --platform "$1"' _ "${{ matrix.arch }}"
          sudo chown "$USER:$USER" ./*.snap
          mv ./*.snap build/linux/
        fi

    # upload build artifacts
    - uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.artifact-name }}
        path: ${{ matrix.artifact-path }}
